#ifndef __PALETTE_DEFINE__
#define __PALETTE_DEFINE__

enum
{
	FONT_COLOR_BLANK = 0,
	FONT_COLOR_NORMAL,
#ifdef UI_COLOR_DISPLAY
	FONT_COLOR_SPECIAL,
	SYSTEM_COLOR_BACKGROUND,
	BUTTON_COLOR_RED,
	BUTTON_COLOR_YELLOW,
	BUTTON_COLOR_GREEN,
	BUTTON_COLOR_BLUE,
	BUTTON_COLOR_PURPLE,
	BUTTON_COLOR_PINK,
	BUTTON_COLOR_AQUA,
	BUTTON_COLOR_SILVER,
	BUTTON_COLOR_NAVY,
	BUTTON_COLOR_LIME,
	CURSOR_COLOR,
#else /* UI_COLOR_DISPLAY */
	FONT_COLOR_BLANK_INVERSE,
	FONT_COLOR_NORMAL_INVERSE,
#endif /* UI_COLOR_DISPLAY */
	MAX_COLORTABLE
};
#endif
